[package]
name = "Metarboard"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "5.0.1"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = {version ="1.0.217", features=["derive"]}
serde_json = "1.0.135"
toml = "0.8.19"
