services:
  metarboard:
    image: realmlist/metarboard:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - TZ=Europe/Amsterdam
      - API_KEY=<your_read_write_api_key_here>
    command: python app.py